#!/bin/bash
display_help() {
	echo "Usage: $(basename $0) OPTIONS [project_dir]

Build and run tetris.

OPTIONS:
	-h --help                show this help

Example:
	Build and run tetris.
	$(basename $0)
"
}

main() {
    local link="https://github.com/mwthinker/Tetris.git"
	local install_dir="MWetris"

	while :; do
		case "$1" in
		-h | --help)
			display_help
			exit 0
			;;
		--) # End of all options
			shift
			break
			;;
		-*)
			echo "Error: Unknown option: $1" >&2
			exit 1
			;;
		*)  # No more options
			if [ ! -z $1 ]; then
				install_dir="$1"
			fi
            # No more options left.
            break
			;;
		esac
	done

	printf "sudo apt-get update\n"
	sudo apt-get update
	printf "sudo apt-get install git cmake build-essential libsdl2-dev libsdl2-ttf-dev libsdl2-net-dev libsdl2-image-dev libsdl2-mixer-dev libglew-dev\n"
	sudo apt-get install git cmake build-essential libsdl2-dev libsdl2-ttf-dev libsdl2-net-dev libsdl2-image-dev libsdl2-mixer-dev libglew-dev
	
	printf "git clone $link $install_dir\n"
    	
	git clone "$link" "$install_dir"
	cd "$install_dir"
	git checkout develop
	git submodule update --init --recursive
	mkdir build2
	cd build2
	
	cmake ..
	make
	
	./MWetris --no-window
}

main "$@"
