#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "Usage: $(basename $0) OPTIONS [project_name]

Create a new mw C++ project using CMake.

OPTIONS:
	-h --help                show this help	
	-n --no-git              git is not initialized

Call manually to add dependencies if \"-n\" flag is used:
git init
git submodule add https://github.com/mwthinker/SdlGui.git
git submodule update --init --recursive
"
	exit 0
fi

if [ "$1" == "-n" ] || [ "$1" == "--no-git" ]; then
	no_git=1
	shift
fi

if [ -z "$1" ]; then
	printf "$0 error, missing 1:st argument." >&2
	exit 1
else
	project_name="$1"
fi

main() {
	src_folder="src"

	local cmake_str="cmake_minimum_required(VERSION 3.6)
project($project_name)
set(CMAKE_MODULE_PATH \${CMAKE_MODULE_PATH} \${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules/ \${CMAKE_CURRENT_SOURCE_DIR}/SdlGui/MwLibrary2/cmake/Modules/)

if (MSVC)
	add_definitions(-D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DWIN32)
else ()
	set(CMAKE_CXX_FLAGS \"-std=c++1y\")
	option(Debug \"Set projects to debug mode.\")
	if (Debug)
		set(CMAKE_BUILD_TYPE \"Debug\" CACHE INTERNAL \"Build type.\")
		add_definitions(-D_DEBUG)
	else ()
		set(CMAKE_BUILD_TYPE \"Release\" CACHE INTERNAL \"Build type.\")
	endif ()
endif ()

# Source files.
set(SOURCES
	src/main.cpp
)

# End of source files.

find_package(SDL2 REQUIRED)
find_package(SDL2_image REQUIRED)
find_package(SDL2_mixer REQUIRED)
find_package(SDL2_ttf REQUIRED)
find_package(GLEW REQUIRED)
find_package(OpenGL REQUIRED)

if (CMAKE_COMPILER_IS_GNUCXX)
	find_package(Threads REQUIRED) # Due to a bug, which forces the user to link to Threads when using #include <thread>.
endif (CMAKE_COMPILER_IS_GNUCXX)

add_subdirectory(SdlGui)

file(COPY data/. DESTINATION \${CMAKE_CURRENT_BINARY_DIR}) # Copy data to build folder.

include_directories(
	\${SDL2_INCLUDE_DIRS} 
	\${SDL2_TTF_INCLUDE_DIRS}
	\${SDL2_MIXER_INCLUDE_DIRS} 
	\${SDL2_IMAGE_INCLUDE_DIRS}
	\${GLEW_INCLUDE_DIRS}
	SdlGui/src
	SdlGui/MwLibrary2/src
	SdlGui/Signal/src
)

add_executable($project_name \${SOURCES})

if (MSVC)
	set_target_properties($project_name PROPERTIES LINK_FLAGS_DEBUG \"/NODEFAULTLIB:msvcrt\")
	set_target_properties($project_name PROPERTIES LINK_FLAGS_RELEASE \"/SUBSYSTEM:windows\")
endif ()

target_link_libraries($project_name
	MwLibrary2
	SdlGui
	\${GLEW_LIBRARIES}
	\${OPENGL_LIBRARIES}
	\${SDL2_LIBRARIES}
	\${SDL2_TTF_LIBRARIES}
	\${SDL2_MIXER_LIBRARIES}
	\${SDL2_IMAGE_LIBRARIES}
	\${CMAKE_THREAD_LIBS_INIT})
"

	mkdir "$project_name"
	cd "$project_name"

	if [ ! "$no_git" ]; then
		git init
		git submodule add https://github.com/mwthinker/SdlGui.git
		git submodule update --init --recursive
	fi

	mkdir "$src_folder"
	mkdir "data"
	
	mkdir "cmake"
	mkdir "cmake/modules"
	
	printf "$cmake_str" > CMakeLists.txt
	
	local cpp_str="
int main(int argc, char** argv) {
	
}\n"
	printf "$cpp_str" > "$src_folder/main.cpp"

	local git_ignore="*.wav
*.7z
*.zip
*.mp3
*.xcf
build
build2
"
	printf "$git_ignore" > .gitignore

local git_attributes="# Auto detect text files and perform LF normalization
* text eol=lf

*.ttf binary
*.png binary

# Custom for Visual Studio
*.cs     diff=csharp
*.sln    merge=union
*.csproj merge=union
*.vbproj merge=union
*.fsproj merge=union
*.dbproj merge=union

# Standard to msysgit
*.doc	 diff=astextplain
*.DOC	 diff=astextplain
*.docx diff=astextplain
*.DOCX diff=astextplain
*.dot  diff=astextplain
*.DOT  diff=astextplain
*.pdf  diff=astextplain
*.PDF	 diff=astextplain
*.rtf	 diff=astextplain
*.RTF	 diff=astextplain
"
	printf "$git_attributes" > .gitattributes
}

main $@
