#!/bin/bash
display_help() {
	echo "Usage: $(basename $0) OPTIONS

Lists the season and episode and in that order.

OPTIONS:
	-h --help                show this help
	-e --episode             list the episode
	-s --season              list the season

Example:
	$(basename $0) \"the.big.bang.theory.S10E16.mp4\"
	10	16
"
}

# Prints the season, if no season, zero is printed
get_season() {
	local season=0
	local file="$1"

	for i in {0..9}; do
		case "$file" in
		*[sS]0"$i"[eE]*)
			season="$i"
			break
			;;		
		*[sS]1"$i"[eE]*)
			season="1$i"
			break
			;;
		esac
	done
	printf "$season"
}

# Prints the episode, if no episode, zero is printed
get_episode() {
	local episode=0
	local file="$1"

	for i in {0..9}; do
		case "$file" in
		*[sS][01][0-9][eE]0"$i"*)
			episode="$i"
			break
			;;		
		*[sS][01][0-9][eE]1"$i"*)
			episode="1$i"
			break
			;;
		*[sS][01][0-9][eE]2"$i"*)
			episode="2$i"
			break
			;;
		esac
	done
	printf "$episode"
}

main() {
	local episode=0
	local season=0
	local filename=""	

	while :; do
		case "$1" in
		-h | --help)
				display_help
				exit 0
				;;
		-e | --episode)
			episode=1
			shift
			;;
		-s | --season)
			season=1
			shift
			;;
		-[se][se])
			episode=1
			season=1
			shift
			;;
		--) # End of all options
			shift
			break
			;;
		-*)
			echo "Error: Unknown option: $1" >&2
			exit 1
			;;
		*)  # No more options
			filename=$@
			shift
			break
		esac
	done

	if [ ! "$filename" ]; then
		echo File is missing as argument >&2
		exit 1
	fi

	filename=$(basename "$filename")

	if (( $episode == 0 )) && (( $season == 0 )); then
		episode=1
		season=1
	fi

	if (( $season == 1 )); then
		get_season "$filename"
	fi

	if (( $episode == 1)); then
		if (( $season == 1 )); then
			printf "\t"
		fi
		get_episode "$filename"
	fi

	echo ""
}

main "$@"
