#!/usr/bin/env bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	printf "\n%s\n\n" "Install updates for the ubuntu distro."
	exit 0
fi

sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
