#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "Usage: $(basename $0) OPTIONS

Install updates for the ubuntu distro.
runs: sudo apt update && sudo apt upgrade && sudo apt dist-upgrade

OPTIONS:
	-h --help                show this help
"
	exit 0
fi

sudo apt update && sudo apt upgrade && sudo apt dist-upgrade
